name: example
description: Examples for align_positioned.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  align_positioned:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
